spring.application.name=rasmoo-microservico

# Configurações do banco de dados
spring.datasource.url=jdbc:mysql://localhost:3308/dbdesv01
spring.datasource.username=root
spring.datasource.password=MNGCC-04xRcxS3EWw7dz
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurações adicionais do Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Porta do servidor
server.port=8080

# Contexto da aplicação
server.servlet.context-path=/minhaapp

# Codificação padrão
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# Nível de log (trace, debug, info, warn, error, fatal, off)
logging.level.root=info

# Arquivo de log
logging.file.name=logs/Ecommerce.log

# Padrão de log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} - %msg%n



# Configurar a porta do Actuator
management.server.port=8081

# Configurar a base path do Actuator
management.endpoints.web.base-path=/actuator
management.endpoints.web.exposure.include=info,health,metrics

# Informações personalizadas para o endpoint /info
info.app.name=Rasmoo Microservico
info.app.description=Este é um serviço de exemplo para demonstração do Actuator.
info.app.version=1.0.0
info.app.maintainer.name=Tiago
info.app.maintainer.email=tiago@example.com

##FLYWAY
# Valida as migrações antes de executar novas
spring.flyway.validate-on-migrate=true
# Limpa e recria todas as tabelas (USE COM CUIDADO EM AMBIENTES DE PRODUÇÃO)
spring.flyway.clean-disabled=true
# Permitir a migração mesmo quando há schemas existentes
spring.flyway.baseline-on-migrate=true

##Configurações do Servidor SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=seuemail@gmail.com
spring.mail.password=suasenha

# Usar STARTTLS para garantir conexão segura
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Codificação e Timeout da conexão
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
